name: "Godot Publish"
description: "Publish from Godot to GitHub Pages"
# NOTE: To update the version of Godot used for automated builds:
# 1. Navigate to the Docker Container registry page for "abarichello/godot-ci"
# 2. Identify a container image that corresponds the the intended build of Godot
# 3. Update the "GODOT_VERSION" Key
# 
# Additional Note:
# - If the "abarichello/godot-ci" container repository ever becomes unmaintained, these containers
#   can be rebuilt by including a version of Godot (possibly stripped down for efficiency) that are
#   called via script in order request a HTML build.
on:
  push:
  workflow_dispatch:

  # schedule:
  #   - cron: "0 6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # NOTE: INSERT Selected Godot Version from Step 3 Below
  GODOT_VERSION: 4.6.1 # Previously: 4.3, 4.5
  EXPORT_NAME: psyche-opoly
  PROJECT_PATH: ./

jobs:

  _01_export_godot_project_to_web:
    name: 01 Export Godot Project to Web
    runs-on: ubuntu-latest

    # Begin Unverified Script
    # NOTE: INSERT Container Version Below from Step 2
    # Container Name from Repository Internal File
    container: barichello/godot-ci:4.6.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Requirement Unverified
        with:
          lfs: true

      - name: Setup Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      
      - name: Run Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      
      # End Unverified Script

      - name: Upload Generated Build Files
        uses: actions/upload-artifact@v4
        with:
          name: ProjectBuild.zip
          path: build/web
      
      - name: Upload Generated Build Formats in a Special Format Required for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  _02_publish_to_github_pages:
    needs: _01_export_godot_project_to_web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    # Permissions for Test GitHub Pages Deployment
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # End Permissions

    # Deploy and Publish to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
